export const FILE_EVENTS={
    MOVE_FILE_TO_FOLDER:'MOVE_FILE_TO_FOLDER',
    COPY_FILE_TO_FOLDER:'COPY_FILE_TO_FOLDER',
    DELETE_FILES:'DELETE_FILES',
    CREATE_FILE:'CREATE_FILE',
    SORT_FILE_BY_FIELD:'SORT_FILE_BY_FIELD',
    UPDATE_FILE:'UPDATE_FILE',
    UPDATE_FILE_NAME:'UPDATE_FILE_NAME',
    UPLOAD_FILES:'UPLOAD_FILES',
    CLOSE_LINK:'CLOSE_LINK',
    SHARE_PERMISSION_CHANGED:'SHARE_PERMISSION_CHANGED',
    SHARE_CHANGED:'SHARE_CHANGED',
    FILE_MOVE_IN:'FILE_MOVE_IN',
    FILE_MOVE:'FILE_MOVE',
    FILE_MOVE_OUT:'FILE_MOVE_OUT',
    REFRESH:'REFRESH',
    ROMOVEFOCUS:'ROMOVEFOCUS',
    FOCUS:'FOCUS',
    SEARCHFILE: 'SEARCHFILE',
    SET_USER_ROLE: 'SET_USER_ROLE',
    CREATE_MODULE_FILE: 'CREATE_MODULE_FILE',
    STOP_SHARE: 'STOP_SHARE',
    SHARE_FILE: 'SHARE_FILE',
    RENAME: 'RENAME_FILE',  // 重命名
  }
  export const NOTIFICATION_EVENTS={
    NOTIFICATION_DELETE:'NOTIFICATION_DELETE',
    NOTIFICATION_DELETEALL:'NOTIFICATION_DELETEALL',
    NOTIFICATION_LENGTH:'NOTIFICATION_LENGTH',
    NOTIFICATION_UPDATE:'NOTIFICATION_UPDATE',
  }
  export const USERINFO_EVENTS={
    USERINFO_UPDATE:'USERINFO_UPDATE',
    UPDATE_PHONE:'UPDATE_PHONE',
  }
  export const EVENTS={
    TAB_CHANGE:'TAB_CHANGE',
    RELOGIN:'RELOGIN',
    SHOW_BINDPHONE:'SHOW_BINDPHONE'
  }
  