export const MESSAGE_TYPE= {
    CREATE: 1, // create dir
    NEW_VERSION: 2,  // 上传新版本
    RENAME: 3,
    MOVE: 4, //共享文件夹内部移动，入从文件A中移动到A.B中（B是A的子文件夹）
    DELETE: 5,
    RESTORE: 6,
    MOVE_IN: 7, //向文件夹中移入某一文件夹
    MOVE_OUT: 8, //从文件夹中移出某一文件
    SET_CURRENT_VERSION: 9,
    // UPLOAD_VERSION: 10, // not used ??
    MULTI_UPLOAD: 11,
    COPY: 12,
    PRAISE_FILE: 13,
  
    JOIN_SHARE: 31,
    LEAVE_SHARE: 32,
    SHARE: 33,
    STOP_SHARE: 34,
    INVITATION: 35,
    REMOVE_INVITATION: 36,
    SET_SHARE_DEFAULT_ROLE: 37,
    SET_USER_ROLE: 38,
    KICK_FROM_SHARE: 39,
    OPEN_LINK: 40, // new 10/2016
    CLOSE_LINK: 41, // new 10/2016
    MODIFY_LINK_LEVEL: 42, // new 10/2016
    ACCEPT_OR_DENY_INVITATION: 43, // new 11/2016
    REMOVED_TEAM_INVITATION_APPLICATION: 44, // new 02/2017
  
    FOCUS_FILE: 47, // new 06/2017
    REMOVE_FOCUS_FILE: 48, // new 06/2017
  
    COMMENT_CREATED: 51,
    COMMENT_CHAT: 52,
    COMMENT_DELETE: 53,
    COMMENT_COMPLETED: 54,
    COMMENT_PRAISE: 55,
    COMMENT_UNCOMPLETED: 56,
  
    DEPARTMENT_ADDMEMBER: 61,
    DEPARTMENT_UPDATE: 62,
    DEPARTMENT_REMOVE_MEMBER: 63,
    DEPARTMENT_UPDATE_MEMBER: 64,
    DEPARTMENT_CREATE: 65,
    DEPARTMENT_REMOVE: 67,
  
    CHAT: 101,
    REQUEST_LINK_SHARE: 201, // new 10/2016
    REQUEST_INVITE_SHARE: 202, // new 10/2016
  
    PAYMENT_MESSAGE: 301,
  
    FILEREVIEW_CREATE: 76,
  
    SET_VERSION_LOG: 112,
  
    PDFTOWORD_NOTIFICATION: 123,     //PDF转WORD右下角的弹出框消息通知     --dzg
    WORDTOPDF_NOTIFICATION: 124,
    PDFTOPPT_NOTIFICATION: 125,
    PPTTOPDF_NOTIFICATION: 126,
    PDFTOEXCEL_NOTIFICATION: 127,
    EXCELTOPDF_NOTIFICATION: 128,
    PDFTOJPG_NOTIFICATION: 129,
    PDFTOHTML_NOTIFICATION: 130,
    PDFTOSPLIT_NOTIFICATION: 131,
    PDFADDWATERMARK_NOTIFICATION: 132,
    PDFMERGE_NOTIFICATION: 133,
    
    INVITE_CONTRIBUTOR: 309,      // ------------------ 投件箱邀请投件人的通知
    INVITE_EVALUATION: 302,      // 邀请参与审批的消息
    EVALUATION_PASS: 303,
    EVALUATION_REJECT: 304,
    ENTERPRISE_BROADCAST: 306,
    FILE_USER_EVLUATION: 307, //用户审批文件
    SALON: 308, //沙龙消息
  
    EVALUATION_COPYTO: 310
  
  }
  