export const HTTP_STATUS = {
    SUCCESS: 200,
    CLIENT_ERROR: 400,
    AUTHENTICATE: 401,
    FORBIDDEN: 403,
    NOT_FOUND: 404,
    SERVER_ERROR: 500,
    BAD_GATEWAY: 502,
    SERVICE_UNAVAILABLE: 503,
    GATEWAY_TIMEOUT: 504
  }
  
  export const RESULT_STATUS = {
    SUCCESS:   0,
    ERROR:     1,
    ERROR_WRONG_PARAMETER: 2,
  
    ERROR_DOWNLOAD_DENY: 4,
    ERROR_UPLOAD_DENY: 5,
    ERROR_OUT_OF_SPACE: 7,
    ERROR_PERMISSION_DENIED: 12,
    ERROR_ORDER_NOT_FOUND: 13,
    ERROR_ORDER_CANCELED: 14,
    ERROR_ORDER_DELETED: 15,
    ERROR_ORDER_WAIT_VERIFY: 16,
    ERROR_ORDER_PAYED: 17,
    ERROR_HAS_UNPAY_ORDER: 18,
  
    ERROR_FILE_NOT_FOUND: 101,
    ERROR_DIRECTORY_CREATE: 109,
    ERROR_FILE_MOVE_TO_YOU: 111,
    ERROR_OUT_OF_VERSION: 133,
    ERROR_OUT_OF_CAD: 134,
    ERROR_OUT_OF_THREED: 135,
    ERROR_FILE_IS_LOCK: 138,
  
  
    ERROR_USER_NOT_FOUND:203,
    ERROR_USER_NOT_LOGIN: 207,
    ERROR_USER_LOG_OFF: 209,
    ERROR_ENTERPRISE_MEMBER_BAN: 224,
    ERROR_OUT_OF_TEAM: 225,
    ERROR_OUT_OF_TEAMMEMBER: 602,
    ERROR_PROFESSION_OUTOFDATE: 226,
    ERROR_ENTERPRISE_OUTOFDATE: 227,
    ERROR_USER_FROZEN: 230,
    ERROR_ENTERPRISE_OUTOFMEMBER: 246,
    ERROR_COULD_NOT_CREATE_TAG: 267,
  
    ERROR_CLIENT_VERSION_NOT_SUPPORT: 100,
    ERROR_TO_BUSY:  302,
    ERROR_ALREADY_IN:  303,
    ERROR_COLLABORATION_NOT_FOUND: 304,
    ERROR_COLLABORATION_DELETE_INTERNAL: 305,
    ERROR_COLLABORATION_CLOSE_INTERNAL: 306,
    ERROR_COLLABORATION_JOIN_DUPLICATE:  307,
    ERROR_COLLABORATION_NOT_JOIN:  308,
    ERROR_SESSION_ALREADY_EXIST: 309,
    ERROR_SESSION_NOT_VALID: 310,
    ERROR_CACHE_STORE_USER_SESSION: 311,
    ERROR_CACHE_GET_SESSION_CID: 312,
    ERROR_DB_FILE_NOT_EXIST: 313,
    ERROR_DB_FILE_NAME_EXIST: 314,
    ERROR_MONGODB_GET_MESSAGE: 315,
    ERROR_PARENT_STILL_IN_TRASH:316,
    ERROR_FILE_DELETE_INTERNAL: 317,
    ERROR_FILE_IS_NOT_SHARED: 318,
    ERROR_FILE_ACCESS_DENIED: 319,
    ERROR_FILE_HAS_SHARING_CHILDREN: 320,
    ERROR_ALREADY_EXISTS: 321,
    ERROR_COULD_NOT_RESTORE: 322,
    ERROR_DEPARTMENT_HAS_CHILD: 323,
    ERROR_DEPARTMENT_NAME_EXISTS: 324,
    ERROR_CANT_REMOVE_ENTERPRISE_OWNER: 325,
    ERROR_FILE_IS_LINKFILE: 326,
    ERROR_WRONG_SHARE_PASSWORD: 327,
    ERROR_DEST_USER_OUT_OF_SPACE: 328,
    ERROR_DEST_USER_OUT_OF_DATE: 329,
    ERROR_FILE_EVALUATING: 330, // file is evaluating
    ERROR_FILE_NOT_EVALUATING: 331, // file is not evaluating
    ERROR_FILE_HAS_NO_EVALUATION: 332, // file is evaluation flow id
    ERROR_EVALUATION_WRONG_STEP: 333, // in wrong step
    ERROR_TMPL_NAME_EXISTS: 334,
    ERROR_NO_MOVE: 335,
    ERROR_MOVE_DEPARTMENT_FILE: 336,
    ERROR_CANT_SHARE_TO_OWNER: 337,
    ERROR_MUST_BIND_PHONE: 338,
    ERROR_GROUP_NAME_EXIST: 339,
  //---------------------- old ---------------------------//
  
  
    ERROR_COULD_NOT_SAVE:  254,
  
    ERROR_NOT_FOUND:404
  }
  